@echo off

SET PORTABLEROOT=%~dp0
SET HOMEDRIVE=%~d0
SET HOMEPATH=%~p0profile
SET USERPROFILE=%PORTABLEROOT%profile
SET CONFIG=%USERPROFILE%\console.config
SET PATH=%PORTABLEROOT%bin;%PORTABLEROOT%bin\console2;%PORTABLEROOT%bin\sysinternals;%PATH%

start console.exe -c "%CONFIG%" -d "%PORTABLEROOT%"